// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW-ow3mu12EZRvwAhpXoz0AhYxstmTBEw',
    appId: '1:135050435511:web:387e346ef885ed9314a632',
    messagingSenderId: '135050435511',
    projectId: 'marketingshoes-682ee',
    authDomain: 'marketingshoes-682ee.firebaseapp.com',
    storageBucket: 'marketingshoes-682ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnxhjvM8aXN7Utfc0wyLInmatQc3hSllM',
    appId: '1:135050435511:android:edf3961ab203d2a914a632',
    messagingSenderId: '135050435511',
    projectId: 'marketingshoes-682ee',
    storageBucket: 'marketingshoes-682ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJMRqvTbPmKuRvB3H2GShDym9z2kyjg8A',
    appId: '1:135050435511:ios:cc015f36d43c6df014a632',
    messagingSenderId: '135050435511',
    projectId: 'marketingshoes-682ee',
    storageBucket: 'marketingshoes-682ee.appspot.com',
    iosBundleId: 'com.example.shoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJMRqvTbPmKuRvB3H2GShDym9z2kyjg8A',
    appId: '1:135050435511:ios:cc015f36d43c6df014a632',
    messagingSenderId: '135050435511',
    projectId: 'marketingshoes-682ee',
    storageBucket: 'marketingshoes-682ee.appspot.com',
    iosBundleId: 'com.example.shoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW-ow3mu12EZRvwAhpXoz0AhYxstmTBEw',
    appId: '1:135050435511:web:618601c25f2dc1e014a632',
    messagingSenderId: '135050435511',
    projectId: 'marketingshoes-682ee',
    authDomain: 'marketingshoes-682ee.firebaseapp.com',
    storageBucket: 'marketingshoes-682ee.appspot.com',
  );
}
